name: build and test on main and release

on:
  push:
    branches: 
      - main
      - 'releases/**'
  pull_request:
    types:
      - opened
      - reopened
      - milestoned

env:
  DOTNET_VERSION: '17.14.0' # The .NET SDK version to use

jobs:
  build:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore

  dev-checks:

    name: Check codebase
    needs: build

    steps:
      - name: Perform unit tests (dev)

      - name: Perform unit tests (QA)

      - name: Static code analysis # TODO: may fail

      - name: BE dependency check

      - name: FE package audit # yarn audit

  deploy-and-seed-test-env: # unless the all checks may be done virtually (in temp container?) then deploy should bes next to last, but seed remain

    name: Deploy and seed on test env
    needs: dev-checks
    steps:
      - name: Deploy on test env

      - name: Seed data

  automated-test-smoke:

    name: Perform API and UI smoke tests
    needs: deploy-and-seed-test-env
    steps:
      - name: Smoke Tests
        run: dotnet test --no-restore --verbosity normal
      # TODO: replace with the one above when tests divided by test categories
      # - name: API smoke tests
      #   run: dotnet test --no-restore --verbosity normal --filter TestCategory=UISmokeTests
      # - name: UI smoke test
      #   run: dotnet test --no-restore --verbosity normal --filter TestCategory=APISmokeTests

  automated-test-regression:

    name: Perform API and UI regression tests
    needs: automated-test-smoke
    steps:
      - name: Regression Tests
        run: dotnet test --no-restore --verbosity normal
      # TODO: replace with the one above when tests divided by test categories
      # - name: API regression tests
      #   run: dotnet test --no-restore --verbosity normal --filter TestCategory=APIRegressionTests
      # - name: UI regression test
      #   run: dotnet test --no-restore --verbosity normal --filter TestCategory=UIRegressionTests

  email-notification:

    name: Inform the pipeline has passed
    needs: automated-test-regression
    steps:
      - name: Send email notification
      # TODO: integrate with team's communicator to send notifications there
